<a href="https://colab.research.google.com/github/Kylerovic11/58013-Linear-Algebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program

In [31]:
import numpy as np

# Define the range of numbers for the table (1 to 10)
start = 1
end = 10

# Create a NumPy array for the range of numbers
numbers = np.arange(start, end + 1)

# Initialize an empty 2D NumPy array for the multiplication table
table = np.zeros((end, end), dtype=int)

# Fill in the multiplication table
for i in range(end):
    table[i, :] = numbers * (i + 1)

# Print the multiplication table
for i in range(end):
    for j in range(end):
        print(f"{table[i, j]:2d}", end="\t")
    print()

 1	 2	 3	 4	 5	 6	 7	 8	 9	10	
 2	 4	 6	 8	10	12	14	16	18	20	
 3	 6	 9	12	15	18	21	24	27	30	
 4	 8	12	16	20	24	28	32	36	40	
 5	10	15	20	25	30	35	40	45	50	
 6	12	18	24	30	36	42	48	54	60	
 7	14	21	28	35	42	49	56	63	70	
 8	16	24	32	40	48	56	64	72	80	
 9	18	27	36	45	54	63	72	81	90	
10	20	30	40	50	60	70	80	90	100	





In relation to Question 1, show a solution that doubles all the values of each element.

In [33]:
import numpy as np

# Define the range of numbers for the table (1 to 10)
start = 1
end = 10

# Create a NumPy array for the range of numbers
numbers = np.arange(start, end + 1)

# Initialize an empty 2D NumPy array for the multiplication table
table = np.zeros((end, end), dtype=int)

# Fill in the multiplication table
for i in range(end):
    table[i, :] = numbers * (i + 1)

# Double all the values in the table
table_doubled = table * 2

# Print the doubled multiplication table
for i in range(end):
    for j in range(end):
        print(f"{table_doubled[i, j]:4d}", end="\t")
    print()

   2	   4	   6	   8	  10	  12	  14	  16	  18	  20	
   4	   8	  12	  16	  20	  24	  28	  32	  36	  40	
   6	  12	  18	  24	  30	  36	  42	  48	  54	  60	
   8	  16	  24	  32	  40	  48	  56	  64	  72	  80	
  10	  20	  30	  40	  50	  60	  70	  80	  90	 100	
  12	  24	  36	  48	  60	  72	  84	  96	 108	 120	
  14	  28	  42	  56	  70	  84	  98	 112	 126	 140	
  16	  32	  48	  64	  80	  96	 112	 128	 144	 160	
  18	  36	  54	  72	  90	 108	 126	 144	 162	 180	
  20	  40	  60	  80	 100	 120	 140	 160	 180	 200	


Create a square matrix that has a diagonal 1's.

In [21]:
A = np.eye(5,5)
print (A)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Create a matrix whose elements are:

In [18]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("the matrix size is:", matrix.size)
print("the matrix shape is:", matrix.shape)
print("the matrix dimention is:", matrix.ndim)


the matrix size is: 12
the matrix shape is: (3, 4)
the matrix dimention is: 2


Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.

In [25]:
import numpy as numpy
arrayOne = numpy.array ([[5, 6, 9],[21, 18, 27]])
arrayOne = numpy.array ([[15, 33, 24],[4, 7, 1]])

sum1 = arrayOne + arrayTwo
print (sum1)
arrOne = (arrayOne**2)
arrTwo = (arrayOne**2)



In [30]:
import numpy as np

# Create two NumPy arrays
arrayOne = numpy.array ([[5, 6, 9],[21, 18, 27]])
arrayOne = numpy.array ([[15, 33, 24],[4, 7, 1]])

# Add the two arrays
result_array = array1 + array2

# Calculate the square of each element in the result array
result_array_squared = np.square(result_array)

print(result_array_squared)


[25 49 81]
